### ISSUE TITLE
fix_latin doesn't fix hex FC?

### ISSUE THREAD

**Issue by monolied** [grantm/encoding-fixlatin#1]
`perl -MEncoding::FixLatin -e 'print "\xFC\n", Encoding::FixLatin::fix_latin("\xFC"), "\n";' | hd`

Hex dump shows:
`00000000  fc 0a fc 0a`

So it seems like the second FC doesn't get converted to UTF-8 "ü", which according to the manual it should ...

I used GRANTM/Encoding-FixLatin-1.04.tar.gz.

Where am I going wrong?

**Comment by grantm** [comment]
Internally, Perl stores characters using a modified form of UTF-8 which is the same as UTF-8 except that some characters in the range 0x80-0xFF are represented using one byte instead of two.  By default, fix_latin returns a character string in Perl's internal encoding.

When you write characters out to a filehandle, you need to set the encoding on the output filehandle using binmode, eg: `binmode(STDOUT, ":utf8")` so that Perl knows how to convert from it's internal representation.  For a 1-liner, you can achieve the same effect with -CO

```
perl -CO -MEncoding::FixLatin -e 'print "\xFC\n", Encoding::FixLatin::fix_latin("\xFC"), "\n";' | hd
```

Note: that will convert both your \xFC bytes.

If you're calling fix_latin immediately before writing the data to a filehandle, you can save some CPU cycles by telling fix_latin not to convert to Perl's internal representation and just return the raw bytes instead:

```
perl -MEncoding::FixLatin -e 'print "\xFC\n", Encoding::FixLatin::fix_latin("\xFC", bytes_only => 1), "\n";' | hd
```

Hope that helps.
